core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@CoreBundle/Controller/"
    type:     annotation

admin_dashboard:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   "/admin"

admin_crud:
    resource: .
    type:     sonata_admin
    prefix:   "/admin"

app_admin:
    resource: "@CoreBundle/Controller/Admin"
    type:     "annotation"
    prefix:   "/admin"