# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        SA\CoreBundle\Entity\Admin: bcrypt

    role_hierarchy:

        ROLE_ADMIN:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_ADMIN
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admins:
            entity: { class: 'SA\CoreBundle\Entity\Admin' }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            context: main_context
            pattern: ^/admin
            provider: admins
            anonymous: ~
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login_check

                default_target_path: sonata_admin_dashboard
                always_use_default_target_path: true

                username_parameter: _admin_email
                password_parameter: _admin_password
                csrf_parameter: _admin_csrf
                csrf_token_id: authenticate_admin
            logout:
                path: app_admin_logout
                target: homepage
        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: '^/admin/login', roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: '^/admin', roles: [ROLE_ADMIN] }        
